"""Add routes table

Revision ID: c053c58c1a34
Revises: 38d69739e913
Create Date: 2026-03-22 21:33:36.212769

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'c053c58c1a34'
down_revision: Union[str, Sequence[str], None] = '38d69739e913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type="LINESTRING", srid=4326), nullable=False),
    sa.Column('is_active', sa.Boolean(), default=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__routes__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__routes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
